version: '3.9'

services:
  backend:
    build: ./backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - JWT_SECRET=${JWT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - FRONTEND_URL=http://localhost:5173
      # - CLIENT_ORIGIN=http://localhost:3000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=awsbuckyt
      - EMAIL_USER=iamyuvrajsingh118@gmail.com
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_RECEIVER=iamyuvrajsingh118@gmail.com
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./backend:/app
    restart: always
    depends_on:
      - frontend

  frontend:
    build: ./frontend
    ports:
      - '3001:80'
    environment:
      - PORT=3000
    volumes:
      - ./frontend:/app
    restart: always
